export const fixtures = [
  {
    'state-province': null,
    domains: ['student.lboro.ac.uk', 'lboro.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.lboro.ac.uk/'],
    name: 'Loughborough University',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['ntu.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.ntu.ac.uk/'],
    name: 'Nottingham Trent University',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['dur.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.dur.ac.uk/'],
    name: 'University of Durham',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['arts.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['https://www.arts.ac.uk'],
    name: 'University of the Arts London',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['abdn.ac.uk', 'aberdeen.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.abdn.ac.uk/'],
    name: 'University of Aberdeen',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['aber.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.aber.ac.uk/'],
    name: 'University of Wales, Aberystwyth',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['abertay.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.abertay.ac.uk/'],
    name: 'University of Abertay Dundee',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['aiuniv.edu'],
    country: 'United Kingdom',
    web_pages: ['http://www.aiuniv.edu/'],
    name: 'American InterContinental University - London',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['aku.edu'],
    country: 'United Kingdom',
    web_pages: ['http://www.aku.edu/'],
    name: 'Aga Khan University',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['anglia.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.anglia.ac.uk/'],
    name: 'Anglia Ruskin University',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['aston.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.aston.ac.uk/'],
    name: 'Aston University',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['aul.edu'],
    country: 'United Kingdom',
    web_pages: ['http://www.aul.edu/'],
    name: 'The American University in London',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['bangor.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.bangor.ac.uk/'],
    name: 'University of Wales, Bangor',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['bath.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.bath.ac.uk/'],
    name: 'University of Bath',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['bathspa.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['https://www.bathspa.ac.uk/'],
    name: 'Bath Spa University',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['bbk.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.bbk.ac.uk/'],
    name: 'Birkbeck College, University of London',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['bcom.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.bcom.ac.uk/'],
    name: 'British College of Osteopathic Medicine',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['bcu.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.bcu.ac.uk/'],
    name: 'Birmingham City University',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['beds.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.beds.ac.uk/'],
    name: 'University of Bedfordshire',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['bham.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.bham.ac.uk/'],
    name: 'University of Birmingham',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['bolton.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.bolton.ac.uk/'],
    name: 'University of Bolton',
    alpha_two_code: 'GB',
  },
  {
    'state-province': null,
    domains: ['bournemouth.ac.uk'],
    country: 'United Kingdom',
    web_pages: ['http://www.bournemouth.ac.uk/'],
    name: 'Bournemouth University',
    alpha_two_code: 'GB',
  },
];
